# Generated by Django 4.2.5 on 2024-08-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction_data',
            old_name='recover_status',
            new_name='recovery_status',
        ),
    ]
