# Generated by Django 4.2.5 on 2024-08-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_rename_recover_status_deduction_data_recovery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_qty', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oi_deal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lane', models.CharField(blank=True, max_length=255, null=True)),
                ('freight_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bol', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
