# Generated by Django 5.1 on 2024-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0006_remove_validation_deducted_sku_is_not_invoiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
