# Generated by Django 5.1 on 2024-08-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0008_rename_ids_validation_ids_bd_validation_ids_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='duplicate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='edi_mismatch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='final_rca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='invalid_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='invalid_amt_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='invalid_amt_2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='invalid_amt_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='invalid_amt_4',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='load_wise',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='rate_wise',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='valid_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='validation_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
