# Generated by Django 5.1 on 2024-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0009_validation_duplicate_validation_edi_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='invoice_count',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
