# Generated by Django 5.1 on 2024-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deduction_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_account', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_reason', models.TextField(blank=True, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_status', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=255, null=True)),
                ('validation', models.CharField(blank=True, max_length=255, null=True)),
                ('invalid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billback', models.CharField(blank=True, max_length=255, null=True)),
                ('billback_date', models.DateField(blank=True, null=True)),
                ('billback_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('recovered_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
