# Generated by Django 5.1 on 2024-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('deducted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducted_qty', models.IntegerField(blank=True, null=True)),
                ('deducted_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('invoice_location', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_reason_code', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_reason', models.TextField(blank=True, null=True)),
                ('backup_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
