# Generated by Django 5.1 on 2024-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_price_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing_validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('deducted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducted_qty', models.IntegerField(blank=True, null=True)),
                ('deducted_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_reason', models.TextField(blank=True, null=True)),
                ('ids', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billed_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pack_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_per_case', models.IntegerField(blank=True, null=True)),
                ('units_per_pack', models.IntegerField(blank=True, null=True)),
                ('packs_per_case', models.IntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('communication_date', models.DateField(blank=True, null=True)),
                ('buyer_approved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('customer_expected_price_lower_than_billed', models.CharField(blank=True, max_length=50, null=True)),
                ('price_change_not_communicated', models.CharField(blank=True, max_length=50, null=True)),
                ('price_change_communicated_late', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_of_measurement_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_ded_vs_Billed_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('mod_issue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('invalid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('valid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('detailed_reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
