# Generated by Django 5.1 on 2024-09-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_backup_data_inv_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_validation',
            name='inv_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
