# Generated by Django 5.1 on 2024-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_pricing_validation_inv_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_validation',
            name='deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
