# Generated by Django 5.1 on 2024-09-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_pricing_validation_deduction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing_validation',
            old_name='billed_price',
            new_name='gross_price',
        ),
        migrations.RenameField(
            model_name='pricing_validation',
            old_name='billed_price_per_qty',
            new_name='gross_price_per_qty',
        ),
    ]
