# Generated by Django 5.1 on 2024-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_rename_billed_price_pricing_validation_gross_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='buyer_approved',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
