# Generated by Django 5.1 on 2024-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_price_change_buyer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_validation',
            name='buyer_approved',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
