# Generated by Django 5.1 on 2024-09-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_pricing_validation_buyer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_validation',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
