# Generated by Django 4.2.5 on 2023-09-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kroger_hrc_vbrk_vbrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vbrp',
            old_name='DP_Cain_Number',
            new_name='DP_Chain_Number',
        ),
    ]
