# Generated by Django 4.2.5 on 2023-11-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_zoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='dedudction_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRC', models.CharField(max_length=255)),
                ('CustomerNumber', models.CharField(max_length=255, verbose_name='Customer#')),
                ('CustomerName', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('CaseId', models.CharField(max_length=255, verbose_name='Case Id')),
                ('Type', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('CreateDate', models.DateField(verbose_name='Create Date')),
                ('CustomerRefNumber', models.CharField(max_length=255, verbose_name='Customer Ref #')),
                ('InvoiceNumber', models.CharField(max_length=255, verbose_name='Invoice Number')),
                ('ClaimNumber', models.CharField(max_length=255, verbose_name='Claim Number')),
                ('OriginalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Amount')),
                ('ReasonCode', models.CharField(max_length=255, verbose_name='Reason Code')),
                ('RootCauseCode', models.CharField(max_length=255, verbose_name='Root Cause Code')),
                ('RootCause', models.CharField(max_length=255)),
                ('InvalidIdentifier', models.CharField(max_length=255)),
                ('InvalidRootCause', models.CharField(max_length=255)),
                ('PromoField1', models.CharField(max_length=255, verbose_name='PromoField1')),
                ('PromoField2', models.CharField(max_length=255, verbose_name='PromoField2')),
                ('PromoField3', models.CharField(max_length=255, verbose_name='PromoField3')),
                ('ClosedOn', models.DateField(verbose_name='Closed On')),
                ('Comments', models.TextField()),
                ('ActionCode', models.CharField(max_length=255, verbose_name='Action Code')),
                ('ActionCodeCategory', models.CharField(max_length=255, verbose_name='Action Code Category')),
            ],
        ),
    ]
