# Generated by Django 4.2.5 on 2023-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dedudction_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='deduction_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRC', models.CharField(max_length=255)),
                ('Customer_Number', models.CharField(max_length=255)),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Case_Id', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Create_Date', models.DateField()),
                ('Customer_Ref_Number', models.CharField(max_length=255)),
                ('Invoice_Number', models.CharField(max_length=255)),
                ('Claim_Number', models.CharField(max_length=255)),
                ('Original_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Reason_Code', models.CharField(max_length=255)),
                ('Root_Cause_Code', models.CharField(max_length=255)),
                ('Root_Cause', models.CharField(max_length=255)),
                ('Invalid_Identifier', models.CharField(max_length=255)),
                ('Invalid_Root_Cause', models.CharField(max_length=255)),
                ('PromoField1', models.CharField(max_length=255)),
                ('PromoField2', models.CharField(max_length=255)),
                ('PromoField3', models.CharField(max_length=255)),
                ('Closed_On', models.DateField()),
                ('Comments', models.TextField()),
                ('Action_Code', models.CharField(max_length=255)),
                ('Action_Code_Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='dedudction_data',
        ),
    ]
