# Generated by Django 4.2.5 on 2023-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deduction_data_delete_dedudction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction_data',
            name='Create_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
