# Generated by Django 4.2.5 on 2023-11-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_deduction_data_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction_data',
            name='Closed_On',
        ),
    ]
