# Generated by Django 4.2.5 on 2023-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_deduction_data_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction_data',
            name='Closed_On',
            field=models.DateField(blank=True, null=True),
        ),
    ]
