# Generated by Django 4.2.5 on 2023-11-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_deduction_data_closed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='vbrk_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('kroger', models.CharField(max_length=255)),
                ('costco', models.CharField(max_length=255)),
            ],
        ),
    ]
