# Generated by Django 4.2.5 on 2023-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_costco_vbrk_ref_costco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vbrk_ref',
            old_name='kroger',
            new_name='Kroger',
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Accrl_Ind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='CsTy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Ctry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Denominator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='HgLvIt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Inv_output',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Numerator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Pr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='PrCat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Prod_Alloc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='SU',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Scale_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Truck_Stor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx2Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx3Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx4Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx5Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx6Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='Tx7Mt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vbrp',
            name='TxMt1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
