# Generated by Django 4.2.5 on 2024-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_test_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
