# Generated by Django 4.2.5 on 2024-08-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_deduction_data_delete_kroger_hrc_delete_vbrk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
