# Generated by Django 4.2.5 on 2024-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('retailer', models.CharField(blank=True, max_length=50, null=True)),
                ('subcategories', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
