# Generated by Django 5.1 on 2024-09-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_invoice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_data',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
