# Generated by Django 5.1 on 2024-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_invoice_data_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_data',
            name='billed_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
