# Generated by Django 4.2.5 on 2024-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backup_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('deducted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducted_qty', models.IntegerField(blank=True, null=True)),
                ('deducted_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('invoice_location', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_reason_code', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_customer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deduction_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_account', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_customer', models.BooleanField(default=False)),
                ('deduction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_reason', models.TextField(blank=True, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_status', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=255, null=True)),
                ('bol', models.CharField(blank=True, max_length=255, null=True)),
                ('pod_status', models.CharField(blank=True, max_length=255, null=True)),
                ('invalid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_qty', models.IntegerField(blank=True, null=True)),
                ('gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oi_deal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_per_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bol', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pod_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bol', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('shortage', models.IntegerField(blank=True, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('returns', models.IntegerField(blank=True, null=True)),
                ('overage', models.IntegerField(blank=True, null=True)),
                ('net_shortage', models.IntegerField(blank=True, null=True)),
                ('customer_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_to_count', models.BooleanField(default=False)),
                ('pod_found', models.BooleanField(default=False)),
            ],
        ),
    ]
