# Generated by Django 5.1 on 2024-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0002_validation_backup_data_ids_deduction_data_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='billed_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
