# Generated by Django 4.2.5 on 2024-09-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0003_alter_validation_billed_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction_data',
            name='deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
