# Generated by Django 4.2.5 on 2024-09-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0008_deduction_data_validation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='invalid_amt',
            new_name='invalid_amount',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='valid_amt',
            new_name='valid_amount',
        ),
    ]
