# Generated by Django 4.2.5 on 2024-09-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0010_workflow_deduction_data_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='sku',
        ),
    ]
