# Generated by Django 4.2.5 on 2024-09-23 21:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0011_remove_workflow_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='billback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='billback_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='billback_package',
            field=models.FileField(default='NoFile.zip', upload_to=main.models.custom_upload_path),
        ),
        migrations.AddField(
            model_name='workflow',
            name='customer_response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='final_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='repayment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='repayment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
